# Generated by Django 3.2.4 on 2021-06-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(blank=True, max_length=25)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.CharField(blank=True, max_length=200)),
                ('mailingAddress', models.CharField(blank=True, max_length=50)),
                ('mailingCityState', models.CharField(blank=True, max_length=35)),
                ('mailingZipcode', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('businessAddress', models.CharField(blank=True, max_length=35)),
                ('businessCity', models.CharField(blank=True, max_length=25)),
                ('businessZipcode', models.CharField(blank=True, max_length=25, null=True)),
                ('businessCountry', models.CharField(blank=True, max_length=25, null=True)),
                ('grouping', models.CharField(blank=True, max_length=200)),
                ('definition', models.CharField(blank=True, max_length=2400)),
                ('businessName', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('businessState', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('businessAddress', models.CharField(blank=True, max_length=35)),
                ('businessCity', models.CharField(blank=True, max_length=25)),
                ('businessZipcode', models.CharField(blank=True, max_length=25, null=True)),
                ('businessCountry', models.CharField(blank=True, max_length=25, null=True)),
                ('businessState', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
