# Generated by Django 3.2.4 on 2021-06-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderSearch',
        ),
    ]
