# Generated by Django 3.2.4 on 2021-06-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_delete_providersearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerfull',
            name='npi',
            field=models.CharField(blank=True, db_index=True, max_length=25),
        ),
    ]
