# Generated by Django 3.2.4 on 2021-06-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_providerfull_npi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerfull',
            name='businessCity',
            field=models.CharField(blank=True, db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='businessState',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='businessZipcode',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='classification',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='firstname',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='lastname',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
