# Generated by Django 3.2.4 on 2021-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20210617_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerfull',
            name='businessCity',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='businessState',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='businessZipcode',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='classification',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='firstname',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='lastname',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='providerfull',
            name='npi',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
