statesUnedited = "AA AK AL AP AR AZ BAJACALIFORNIA CA CADIZ CO CT DC DE FL GA GU GUAYAS HI IA ID IL IN KINGSTON KS KY LA MA MD ME MI MN MO MP MS MT NC ND NE NH NJ NM NV NY OH OK ONTARIO OR PA PR PW RI SC SD TN TX UT VA VI VT WA WI WV WY"
statesElements = statesUnedited.split(" ")
print(statesElements)